algoritmo "exercicio_16"

var
Cig_dias, cig_anos: inteiro
mvida, cig_pass,diastotal, anodias: real





inicio
      Escreva("Quantos cigarros você fuma por dia? ")
      Leia(cig_dias)
      Escreva("Você fuma a quantos anos? ")
      Leia(cig_anos)
      mvida <- cig_dias * 10
      anodias <- mvida * 365
      diastotal <- anodias/1440
      Escreval ("Dias de vida perdido ",diastotal," dias.")

      
      
      



fimalgoritmo