algoritmo "exercicio_14"

var
km, pdias, pkm, ptotal: real
dias: inteiro

inicio
      Escreva ("Km pecorridos: ")
      Leia (km)
      Escreva ("Dias alugado: ")
      Leia (dias)
      pdias <- dias * 90.00
      pkm <- km * 0.20
      ptotal <- Pdias + Pkm
      Escreval ("Preço por dias alugado é de R$",pdias:2:3,".")
      Escreval ("Preço por km rodado é de R$",pkm:3:3,".")
      Escreval("Preço total:R$",ptotal:3:3,".")
      

fimalgoritmo